---

- hosts: all

  tasks:

  - name: ensure apt cache is up to date
    apt: update_cache=yes
    become: yes

  - name: ensure all packages are up to date
    apt: upgrade=dist
    become: yes

  - name: ensure that java is installed
    apt: name=openjdk-8-jdk state=present
    become: yes

  - name: ensure that git is installed
    apt: name=git state=present
    become: yes

  - name: ensure that unzip is installed
    apt: name=unzip update_cache=yes state=present
    become: yes

  - name: reboot if required
    command: /sbin/reboot removes=/var/run/reboot-required
    become: yes

  - name: wait for host in case reboot occured
    local_action: wait_for host={{ ansible_ssh_host }} port=22 state=started


- hosts: ci-master

  tasks:

  - name: ensure the instance hostname is set to ci-master
    hostname: name=ci-master
    become: yes

  - name: ensure that the hosts file has the hostname ci-master
    lineinfile: dest=/etc/hosts regexp='^127\.0\.0\.1 localhost' line="127.0.0.1 localhost ci-master"
    become: yes

  - name: ensure that the go server deb has been downloaded
    get_url: url=https://download.gocd.org/binaries/17.11.0-5520/deb/go-server_17.11.0-5520_all.deb dest=/tmp/go-server.deb

  - name: ensure that the go server deb is installed
    raw: sudo dpkg --force-confold -i /tmp/go-server.deb

  - name: ensure that the go server is running
    service: name=go-server state=started
    become: yes


- hosts: ci-slave

  tasks:

  - name: ensure the instance hostname is set to ci-slave
    hostname: name=ci-slave
    become: yes

  - name: ensure that the hosts file has the hostname ci-slave
    lineinfile: dest=/etc/hosts regexp='^127\.0\.0\.1 localhost' line="127.0.0.1 localhost ci-slave"
    become: yes

  - name: ensure that the go agent deb has been downloaded
    get_url: url=https://download.gocd.org/binaries/17.11.0-5520/deb/go-agent_17.11.0-5520_all.deb dest=/tmp/go-agent.deb

  - name: ensure that the go agent deb is installed
    raw: sudo dpkg --force-confold -i /tmp/go-agent.deb

  - name: ensure that the go agent is running
    service: name=go-agent state=started
    become: yes

  - name: ensure that the go agent knows where to find the go server
    lineinfile: dest=/etc/default/go-agent regexp='^GO_SERVER=' line="GO_SERVER={{ ci_master_private_ip }}"
    notify: restart the go agent
    become: yes

  - name: ensure that the leiningen bootstrap script has been downloaded
    get_url: url=https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein dest=/usr/local/bin/lein mode=755
    become: yes

  - name: ensure that pip is installed
    apt: name=python3-pip state=present
    become: yes

  - name: ensure that the aws cli is installed
    pip: name=awscli
    become: yes

  - name: ensure that ruby is installed
    apt: name=ruby2.3 state=present
    become: yes


  handlers:

  - name: restart the go agent
    service: name=go-agent state=restarted
    become: yes
